notifier:
    messages:
      - 'A MESSAGE'
    enabled: true
    chat_id: <CHAT_ID>
    token: <TOKEN>
providers:
    provider_a:
        base_url: <URL>
        sources:
          - <PATH>
disable_ssl: true | false
highlighters: ''
filters: false
infinite_frequency: false    # set it to `true` to keep the script running forever (30 secs sleep between iterations)
